[jars] fix maven_id dictionary encoding
The dictionary must contain string types, not byte arrays.

Causes an exception when packing strings with Python3:

  [sos.sosreport:setup] executing 'sosreport -vvv --batch --debug -o jars'
   Setting up plugins ...
  Traceback (most recent call last):
    File "./sosreport", line 25, in <module>
      main(sys.argv[1:])
    File "/home/breeves/src/git/sos/sos/sosreport.py", line 1632, in main
      sos.execute()
  TypeError: key b'version' is not a string

Resolves: #984.

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>