[sos] raise exceptions in SoS._init_component() when --debug
An exception in SoS._init_component() currently leads to a fairly
terse error even with --debug:

  # sos report -vv --batch --debug
  Could not initialize 'report': dictionary update sequence element #0 has length 1; 2 is required

By propagating the exception when --debug is given we get the full
backtrace on the terminal:

  # sos report -vv --batch --debug
  Could not initialize 'report': dictionary update sequence element #0 has length 1; 2 is required
  Traceback (most recent call last):
    File "/home/breeves/src/git/sos/bin/sos", line 21, in <module>
      sos = SoS(sys.argv[1:])
    File "/home/breeves/src/git/sos/sos/__init__.py", line 112, in __init__
      self._init_component()
    File "/home/breeves/src/git/sos/sos/__init__.py", line 153, in _init_component
      raise err
    File "/home/breeves/src/git/sos/sos/__init__.py", line 149, in _init_component
      self.cmdline)
    File "/home/breeves/src/git/sos/sos/report/__init__.py", line 118, in __init__
      super(SoSReport, self).__init__(parser, args, cmdline)
    File "/home/breeves/src/git/sos/sos/component.py", line 98, in __init__
      self.policy = sos.policies.load(sysroot=self.opts.sysroot)
    File "/home/breeves/src/git/sos/sos/policies/__init__.py", line 60, in load
      if policy.check(remote=remote_check):
    File "/home/breeves/src/git/sos/sos/policies/cos.py", line 30, in check
      os_release = dict(line.strip().split('=') for line in fp
  ValueError: dictionary update sequence element #0 has length 1; 2 is required

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>
Signed-off-by: Jake Hunsaker <jhunsake@redhat.com>