[report] check for symlink before rmtree when opt estimate-only is use
Check if the dir is also symlink before performing rmtree()
method so that unlink() method can be used instead.

Traceback (most recent call last):
  File "./bin/sos", line 22, in <module>
    sos.execute()
  File "/tmp/sos/sos/__init__.py", line 186, in execute
    self._component.execute()
OSError: Cannot call rmtree on a symbolic link

Closes: #2727

Signed-off-by: Eric Desrochers <eric.desrochers@canonical.com>