[suse] fix constructor sysroot argument
The Policy class hierarchy requires a 'sysroot' kwarg for class
constructors. This is used to pass the location of the actual
host root file system for container configurations.

The SuSE policy is currently missing this argument, leading to an
exception during policy loading:

  Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 25, in
  main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1592, in
  main
  sos = SoSReport(args)
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 676, in
  init
  self.policy = sos.policies.load(sysroot=self.opts.sysroot)
  File "/usr/lib/python2.7/site-packages/sos/policies/init.py", line 38,
  in load
  cache['policy'] = policy(sysroot=sysroot)
  TypeError: init() got an unexpected keyword argument 'sysroot'

Fixes #809.

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>