Skipping py2 only decorated test if condition is true
Debian/Ubuntu latest release are python3 only by default.

Causing the following during unittest run:

$ nosetests3 -v --with-cover --cover-package=sos --cover-html
======================================================================
FAIL: test_output (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/gh/sos-3.9/tests/utilities_tests.py", line 62, in test_output
    self.assertEquals(result['status'], 0)
AssertionError: 127 != 0

======================================================================
FAIL: test_shell_out (utilities_tests.ExecutableTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/gh/sos-3.9/tests/utilities_tests.py", line 80, in test_shell_out
    self.assertEquals("executed\n", shell_out(path))
AssertionError: 'executed\n' != ''
- executed

Closes: #1885

Co-authored-by: Louis Bouchard <louis@ubuntu.com>
Signed-off-by: Eric Desrochers <eric.desrochers@canonical.com