[sosreport] disable the 'zip' compression type
The Zip archive format is little used and has been broken for
some time:

   Unexpected exception setting up archive:
  Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1092, in prework
      self._set_archive()
    File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 679, in _set_archive
      self.archive = ZipFileArchive(archive_name, self.tmpdir)
  TypeError: __init__() takes exactly 2 arguments (3 given)
  __init__() takes exactly 2 arguments (3 given)

Remove it from the allowed options list for --compression-type.

The supporting Archive classes can be removed in a separate commit.

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>