Fix config file regression
Changes in the organisation of sos in commit 6ea48cb broke the
reading of custom configuration files (either the default
/etc/sos.conf or one specified on the command line using
--config-file):

Traceback (most recent call last):
  File "/usr/sbin/sosreport", line 23, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1167, in main
    sos.execute()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1133, in execute
    self._set_tunables()
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 798, in _set_tunables
    if not opt.split('.')[0] in self.disabled:
AttributeError: 'SoSReport' object has no attribute 'disabled'

The code attempts to reference the obsolete 'disabled' list of
plug-ins (rather than calling self._get_disabled_plugins()) and
failed to initialise the plugopts list to an empty deque.

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>