[sar] fix directory list variable name
One dirList was missed in commit d4ebd07:

  Traceback (most recent call last):
    File "/usr/sbin/sosreport", line 23, in <module>
      main(sys.argv[1:])
    File "/usr/lib/python2.7/site-packages/sos/sosreport.py", line 1229, in main
      sos.execute()
  NameError: global name 'dirList' is not defined

  > /usr/lib/python2.7/site-packages/sos/plugins/sar.py(67)setup()
  -> if sar_filename not in dirList:

Signed-off-by: Bryn M. Reeves <bmr@redhat.com>