[archive] handle OSErrors
If file/folder will be present during file list creation, but will be
missing during collection OSError will throw exception

FileNotFoundError: [Errno 2] No such file or directory

Added handling of OSError into sos/archive.py and new log message with
info level to sos_logs/sos.log

Separated IOError and OSError in sos/archive.py.
Removed handle only if e.errno == 2 as all errors should be logged.
Fixed pycodestyle violations.

Resolves: #1890

Signed-off-by: Jan Jansky <jjansky@redhat.com>