[policies] Fix setting the custom name_pattern
Added initialization of date variable, so that it's possible to set the
custom name_pattern.

Without the fix, if the name_pattern is set in the plugin to be something
else than 'legacy' or 'friendly', the report generation will fail to
error

UnboundLocalError: local variable 'date' referenced before assignment

Signed-off-by: Ville Heikkinen <ville.heikkinen@nokia.com>