[plugins] Fix add_copy_spec's maxage
The `maxage` argument in PlugIn's `add_copy_spec` method doesn't work,
and when it is passed it will raise an exception:

   TypeError: unsupported operand type(s) for -: 'float' and
   'datetime.datetime'

This patch fixes this issue by making sure that the code compares two
floating point numbers representing the seconds passed since Epoch.

Closes: #3675
Signed-off-by: Gorka Eguileor <geguileo@redhat.com>